spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC
#    username: your_mysql_username
#    password: your_mysql_password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
jwt:
  secret: dkf8sl30nfi39ckqpwne29xmaodlkensl
  expiration: 3600000